name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # Checkout Playwright repo
      - name: Checkout Playwright Repo
        uses: actions/checkout@v4

      # Checkout ShopKart repo
      - name: Checkout ShopKart App
        uses: actions/checkout@v4
        with:
          repository: jaisingh-builds/sdet-retail-app
          ref: shopkart
          path: sdet-retail-app

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install Playwright dependencies
      - name: Install Playwright Dependencies
        run: npm install

      # Install ShopKart root dependencies
      - name: Install ShopKart Root Dependencies
        run: |
          cd sdet-retail-app
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd sdet-retail-app/frontend
          npm install

      - name: Install Backend Dependencies
        run: |
          cd sdet-retail-app/backend
          npm install


      # Create .env
      - name: Create .env
        run: |
          cd sdet-retail-app
          cp .env.example .env

      # Verify Vite installation
      - name: Verify Vite
        run: |
          cd sdet-retail-app/frontend
          npx vite --version

      # Start ShopKart
      - name: Start ShopKart
        run: |
          cd sdet-retail-app
          chmod +x scripts/shopkart-start.sh
          ./scripts/shopkart-start.sh > app.log 2>&1 &
          sleep